services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    restart: unless-stopped

  backend:
    build: .
    container_name: mama_put_backend
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    env_file:
      - .env

  frontend:
    build: ./frontend
    container_name: react-frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
